# Generated by Django 5.2.6 on 2025-09-29 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto', max_length=200)),
                ('responsable', models.CharField(help_text='Persona responsable del proyecto', max_length=100)),
                ('involucrados', models.TextField(blank=True, help_text='Lista de personas involucradas en el proyecto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del proyecto')),
                ('materiales', models.TextField(blank=True, help_text='Lista de materiales necesarios')),
                ('lugar', models.CharField(blank=True, help_text='Ubicación donde se desarrolla el proyecto', max_length=300)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del proyecto')),
                ('fecha_final', models.DateField(blank=True, help_text='Fecha de finalización prevista', null=True)),
                ('recursivo', models.BooleanField(default=False, help_text='¿Es un proyecto que se repite periódicamente?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='core.asociacionvecinal')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
