# Generated by Django 5.2.6 on 2025-09-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateTimeField()),
                ('duracion', models.DurationField(blank=True, help_text='Duración del evento (ej: 2:30:00 para 2h 30min)', null=True)),
                ('colaboradores', models.TextField(blank=True, help_text='Lista de colaboradores o entidades que participaron')),
                ('evaluacion', models.PositiveSmallIntegerField(blank=True, choices=[(1, '⭐ Muy Malo'), (2, '⭐⭐ Malo'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')], help_text='Evaluación del evento (1-5 estrellas)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.asociacionvecinal')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
    ]
