# Generated by Django 5.2.6 on 2025-09-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_observaciones'),
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Socia responsable del evento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsable', to='socias.socia'),
        ),
    ]
