# Generated by Django 5.2.6 on 2025-09-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_responsable'),
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
    ]
