# Generated by Django 5.2.6 on 2025-11-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_remove_evento_created_at_remove_evento_updated_at'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Socia responsable del evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsable', to='socias.socia'),
        ),
    ]
