# Generated by Django 5.2.6 on 2025-11-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_alter_evento_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='lugar',
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar_direccion',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección del Lugar'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar_nombre',
            field=models.CharField(blank=True, help_text='Ej: Centro Cívico, Plaza Mayor...', max_length=300, verbose_name='Nombre del Lugar'),
        ),
    ]
