# Generated by Django 5.2.6 on 2025-11-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='evaluacion',
        ),
    ]
