# Generated by Django 5.2.6 on 2025-11-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_remove_evento_evaluacion'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto al que pertenece este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='proyectos.proyecto'),
        ),
    ]
