# Generated by Django 5.2.6 on 2025-11-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asociacionvecinal_drive_credentials'),
        ('eventos', '0013_evento_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='asociacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='core.asociacionvecinal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='direccion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='lugar',
            unique_together={('asociacion', 'nombre')},
        ),
    ]
