# Generated by Django 5.2.6 on 2025-11-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asociacionvecinal_drive_credentials'),
        ('eventos', '0014_lugar_asociacion_alter_lugar_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='asociacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugares', to='core.asociacionvecinal'),
        ),
    ]
