# Generated by Django 5.2.6 on 2025-11-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_alter_lugar_asociacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lugar',
            name='cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del lugar y sus características'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='pais',
            field=models.CharField(blank=True, default='España', max_length=100),
        ),
    ]
