# Generated by Django 5.2.6 on 2025-11-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_persona_contacto_persona_le_conoce_persona_proyecto_and_more'),
        ('eventos', '0016_lugar_ciudad_lugar_cp_lugar_descripcion_lugar_numero_and_more'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(blank=True, help_text='Seleccionar un lugar registrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.lugar', verbose_name='Lugar (Selección)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='materiales_utilizados',
            field=models.ManyToManyField(blank=True, help_text='Materiales utilizados en el evento', related_name='eventos', to='entidades.material'),
        ),
        migrations.AddField(
            model_name='evento',
            name='personas_involucradas',
            field=models.ManyToManyField(blank=True, help_text='Personas externas que participan en el evento', related_name='eventos_involucrada', to='entidades.persona'),
        ),
        migrations.AddField(
            model_name='evento',
            name='socias_involucradas',
            field=models.ManyToManyField(blank=True, help_text='Socias que participan en el evento', related_name='eventos_involucrada', to='socias.socia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='colaboradores',
            field=models.TextField(blank=True, help_text='Lista de colaboradores o entidades que participaron (Texto libre)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar_nombre',
            field=models.CharField(blank=True, help_text='Ej: Centro Cívico, Plaza Mayor...', max_length=300, verbose_name='Nombre del Lugar (Texto)'),
        ),
    ]
