# Generated by Django 5.2.6 on 2025-09-29 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionVecinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Asociación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('numero_registro', models.CharField(max_length=50, unique=True, verbose_name='Número de Registro')),
                ('distrito', models.CharField(blank=True, max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Asociación Vecinal',
                'verbose_name_plural': 'Asociaciones Vecinales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Miembro'), ('admin', 'Administrador de Asociación')], default='member', max_length=10, verbose_name='Rol en la Asociación')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(blank=True, help_text='Asociación a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.asociacionvecinal', verbose_name='Asociación Vecinal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
