# Generated by Django 5.2.6 on 2025-09-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='asociacion',
            field=models.ForeignKey(blank=True, help_text='Asociación a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asociacionvecinal', verbose_name='Asociación Vecinal'),
        ),
        migrations.DeleteModel(
            name='AsociacionVecinal',
        ),
    ]
