# Generated by Django 5.2.6 on 2025-09-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas y observaciones adicionales sobre el evento'),
        ),
    ]
