# Generated by Django 5.2.6 on 2025-09-30 10:41

from django.db import migrations


def asignar_responsables_eventos(apps, schema_editor):
    """Asignar responsables a eventos existentes"""
    Evento = apps.get_model('eventos', 'Evento')
    Socia = apps.get_model('socias', 'Socia')

    # Para cada evento sin responsable, asignar la primera socia de su asociación
    for evento in Evento.objects.filter(responsable__isnull=True):
        primera_socia = Socia.objects.filter(asociacion=evento.asociacion).first()
        if primera_socia:
            evento.responsable = primera_socia
            evento.save()
            print(f"Asignado responsable {primera_socia.nombre} {primera_socia.apellidos} al evento '{evento.nombre}'")


def reversa_asignar_responsables(apps, schema_editor):
    """Función reversa (opcional)"""
    # No hacemos nada en la reversa para mantener los datos
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_responsable_alter_evento_participantes_and_more'),
        ('socias', '__latest__'),  # Aseguramos que las socias estén disponibles
    ]

    operations = [
        migrations.RunPython(asignar_responsables_eventos, reversa_asignar_responsables),
    ]
