# Generated by Django 5.2.6 on 2025-09-30 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20250930_1241'),
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='responsable',
            field=models.ForeignKey(help_text='Socia responsable del evento', on_delete=django.db.models.deletion.PROTECT, related_name='eventos_responsable', to='socias.socia'),
        ),
    ]
