# Generated by Django 5.2.6 on 2025-09-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_responsable'),
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=100)),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos de la persona', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('asociacion', models.CharField(blank=True, help_text='Asociación o entidad a la que pertenece (opcional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona Externa',
                'verbose_name_plural': 'Personas Externas',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
    ]
