# Generated by Django 5.2.6 on 2025-09-30 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_responsable'),
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=100)),
                ('apellidos', models.CharField(blank=True, help_text='Apellidos de la persona', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email de contacto', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('asociacion', models.CharField(blank=True, help_text='Asociación o entidad a la que pertenece (opcional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona Externa',
                'verbose_name_plural': 'Personas Externas',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='participanteevento',
            options={'ordering': ['socia__apellidos', 'persona_externa__apellidos'], 'verbose_name': 'Participante de Evento', 'verbose_name_plural': 'Participantes de Eventos'},
        ),
        migrations.RemoveField(
            model_name='participanteevento',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='participanteevento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participanteevento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='participanteevento',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='participanteevento',
            name='socia',
            field=models.ForeignKey(blank=True, help_text='Si el participante es una socia, selecciónala aquí', null=True, on_delete=django.db.models.deletion.CASCADE, to='socias.socia'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='persona_externa',
            field=models.ForeignKey(blank=True, help_text='Si el participante es una persona externa, selecciónala aquí', null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.personaexterna'),
        ),
        migrations.AddConstraint(
            model_name='participanteevento',
            constraint=models.CheckConstraint(condition=models.Q(('socia__isnull', False), ('persona_externa__isnull', False), _connector='OR'), name='participante_debe_tener_socia_o_persona_externa'),
        ),
        migrations.AddConstraint(
            model_name='participanteevento',
            constraint=models.CheckConstraint(condition=models.Q(('socia__isnull', False), ('persona_externa__isnull', False), _negated=True), name='participante_no_puede_ser_socia_y_externa'),
        ),
    ]
