# Generated by Django 5.2.6 on 2025-10-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_remove_participant_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonaExterna',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='updated_at',
        ),
    ]
