"""
Django settings for asonet_django project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
if getattr(sys, 'frozen', False):
    # Ejecutándose como PyInstaller bundle (EXE)
    # BASE_DIR apunta a la carpeta temporal _MEIPASS donde están los assets
    BASE_DIR = Path(sys._MEIPASS)
    # DB_DIR apunta a la carpeta del ejecutable para persistencia
    DB_DIR = Path(sys.executable).parent
else:
    # Ejecución normal (Desarrollo)
    BASE_DIR = Path(__file__).resolve().parent.parent
    DB_DIR = BASE_DIR

# Load environment variables from .env file in the root of the workspace
# En modo EXE, buscamos el .env junto al ejecutable
if getattr(sys, 'frozen', False):
    # Prioridad 1: config.env (para evitar problemas con archivos ocultos en Mac)
    env_path = DB_DIR / 'config.env'
    if not env_path.exists():
        # Prioridad 2: .env (legacy)
        env_path = DB_DIR / '.env'
else:
    env_path = BASE_DIR.parent / '.env'

print(f"Loading .env from: {env_path}")
if env_path.exists():
    print(".env file found!")
    load_dotenv(env_path)
else:
    print(".env file NOT found!")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=r)7a+lamvyun3ec&g67sx8u6n1^p*pa-q^0zykwawj9u@&=$e'

# SECURITY WARNING: don't run with debug turned on in production!
# Si es un ejecutable (frozen), por defecto DEBUG es False para asegurar que Whitenoise sirva los estáticos.
# Si es desarrollo, por defecto es True.
if getattr(sys, 'frozen', False):
    DEBUG = os.getenv('DEBUG', 'False') == 'True'
else:
    DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']  # Permitir todos los hosts para facilitar despliegue en PythonAnywhere

# API Keys
GEOAPIFY_API_KEY = os.getenv('GEOAPIFY_API_KEY')
GEOAPIFY_BIAS_LAT = os.getenv('GEOAPIFY_BIAS_LAT', '40.416775') # Default Madrid
GEOAPIFY_BIAS_LON = os.getenv('GEOAPIFY_BIAS_LON', '-3.703790') # Default Madrid
GEOAPIFY_COUNTRY_CODE = os.getenv('GEOAPIFY_COUNTRY_CODE', 'es')

# API Configuration
# En producción (PythonAnywhere), esto debe ser https://tu-usuario.pythonanywhere.com/api/v1
API_BASE_URL = os.getenv('API_BASE_URL', 'http://localhost:8000/api/v1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',          # App base con modelos centrales
    'users',         # Autenticación y usuarios web
    'socias',        # Gestión de socias
    'finanzas',      # Contabilidad y finanzas
    'eventos',       # Actividades y eventos
    'proyectos',     # Gestión de proyectos
    'entidades',     # Gestión de entidades y personas externas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Whitenoise para archivos estáticos en Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'asonet_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_settings',
            ],
        },
    },
]

# Configuración específica para PyInstaller: Añadir rutas de plantillas explícitamente
if getattr(sys, 'frozen', False):
    # Lista de apps que tienen templates
    APPS_WITH_TEMPLATES = ['core', 'users', 'socias', 'finanzas', 'eventos', 'proyectos', 'entidades']
    for app in APPS_WITH_TEMPLATES:
        # En el spec file, copiamos templates a: app/templates
        # BASE_DIR es sys._MEIPASS
        template_path = BASE_DIR / app / 'templates'
        if template_path.exists():
            TEMPLATES[0]['DIRS'].append(str(template_path))


WSGI_APPLICATION = 'asonet_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde collectstatic recopilará los archivos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directorios adicionales donde buscar archivos estáticos (desarrollo)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Configuración de Correo ---
# Si existen variables de entorno para email, usa SMTP (correo real).
# Si no, usa la consola (desarrollo).

PASSWORD_RESET_TIMEOUT = 900  # 15 minutos en segundos

if os.getenv('EMAIL_HOST_USER'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    # Modo Desarrollo: Imprime en consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'admin@asonet.local'
