# Generated by Django 5.2.6 on 2025-11-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.CharField(blank=True, help_text='Persona responsable del proyecto', max_length=100, null=True),
        ),
    ]
