# Generated by Django 5.2.6 on 2025-11-27 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_responsable'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Socia responsable del proyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_responsable', to='socias.socia'),
        ),
    ]
