# Generated by Django 5.2.6 on 2025-11-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_persona_contacto_persona_le_conoce_persona_proyecto_and_more'),
        ('eventos', '0017_evento_lugar_evento_materiales_utilizados_and_more'),
        ('proyectos', '0003_alter_proyecto_responsable'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='lugar_fk',
            field=models.ForeignKey(blank=True, help_text='Lugar registrado en el sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='eventos.lugar', verbose_name='Lugar (Selección)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='materiales_necesarios',
            field=models.ManyToManyField(blank=True, help_text='Materiales del inventario necesarios', related_name='proyectos', to='entidades.material'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='personas_involucradas',
            field=models.ManyToManyField(blank=True, help_text='Personas externas que participan en el proyecto', related_name='proyectos_involucrada', to='entidades.persona'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='socias_involucradas',
            field=models.ManyToManyField(blank=True, help_text='Socias que participan en el proyecto', related_name='proyectos_involucrada', to='socias.socia'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='involucrados',
            field=models.TextField(blank=True, help_text='Lista de personas involucradas en el proyecto (Texto libre)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='lugar',
            field=models.CharField(blank=True, help_text='Ubicación donde se desarrolla el proyecto (Texto libre)', max_length=300),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='materiales',
            field=models.TextField(blank=True, help_text='Lista de materiales necesarios (Texto libre)'),
        ),
    ]
