# Generated by Django 5.2.6 on 2025-09-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo para ingresos, negativo para gastos', max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_transaccion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('entidad', models.CharField(blank=True, help_text='Banco, proveedor, etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.asociacionvecinal')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
