# Generated by Django 5.2.6 on 2025-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='drive_file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='drive_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
