# Generated by Django 5.2.6 on 2025-11-25 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_transaccion_drive_file_id_and_more'),
        ('proyectos', '0001_initial'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='socia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='socias.socia'),
        ),
    ]
