# Generated by Django 5.2.6 on 2025-11-27 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asociacionvecinal_drive_credentials'),
        ('entidades', '0001_initial'),
        ('eventos', '0016_lugar_ciudad_lugar_cp_lugar_descripcion_lugar_numero_and_more'),
        ('finanzas', '0003_transaccion_proyecto_transaccion_socia'),
        ('proyectos', '0003_alter_proyecto_responsable'),
        ('socias', '0004_socia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contacto',
            field=models.CharField(blank=True, help_text='Información de contacto adicional o rol', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='le_conoce',
            field=models.ManyToManyField(blank=True, help_text='Socias que conocen a esta persona', related_name='conocidos_externos', to='socias.socia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Proyecto en el que participa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas_externas', to='proyectos.proyecto'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('uso', models.TextField(blank=True, help_text='Para qué se utiliza este material')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor estimado o precio de compra', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.asociacionvecinal')),
                ('encargado_persona', models.ForeignKey(blank=True, help_text='Persona externa encargada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_a_cargo', to='entidades.persona')),
                ('encargado_socia', models.ForeignKey(blank=True, help_text='Socia encargada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_a_cargo', to='socias.socia')),
                ('lugar', models.ForeignKey(blank=True, help_text='Ubicación del material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='eventos.lugar')),
                ('transaccion_compra', models.ForeignKey(blank=True, help_text='Transacción de compra asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_comprados', to='finanzas.transaccion')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
