# Generated by Django 5.2.6 on 2025-11-27 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asociacionvecinal_drive_credentials'),
        ('users', '0003_admininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='asociacion',
            field=models.ForeignKey(blank=True, help_text='Si se selecciona, el usuario será administrador de esta asociación. Si se deja vacío, será Superusuario del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asociacionvecinal', verbose_name='Asociación (Dejar vacío para Superusuario)'),
        ),
    ]
