# Generated by Django 5.2.6 on 2025-11-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociacionvecinal',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Carpeta Google Drive'),
        ),
    ]
