# Generated by Django 5.2.6 on 2025-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asociacionvecinal_drive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociacionvecinal',
            name='drive_credentials',
            field=models.TextField(blank=True, null=True, verbose_name='Credenciales Drive (JSON)'),
        ),
    ]
