# Generated by Django 5.2.6 on 2025-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socias', '0002_alter_socia_numero_socia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='escalera',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='socia',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='socia',
            name='piso',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
