# Generated by Django 5.2.6 on 2025-11-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socias', '0003_socia_escalera_socia_numero_socia_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='socia',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
