# Generated by Django 5.2.6 on 2025-09-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socia', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(default='España', max_length=100)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False, help_text='¿Ha pagado la cuota?')),
                ('descripcion', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socias', to='core.asociacionvecinal')),
            ],
            options={
                'verbose_name': 'Socia',
                'verbose_name_plural': 'Socias',
                'ordering': ['numero_socia'],
                'unique_together': {('asociacion', 'numero_socia')},
            },
        ),
    ]
