# Generated by Django 5.2.6 on 2025-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socia',
            name='numero_socia',
            field=models.CharField(max_length=20),
        ),
    ]
